# Generated by Django 3.1 on 2020-08-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200817_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='state',
        ),
        migrations.AddField(
            model_name='acutationlisting',
            name='state',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
