# Generated by Django 3.1 on 2020-08-20 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200818_2227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcutationListing',
            new_name='AuctionsListing',
        ),
    ]
