# Generated by Django 3.1 on 2020-08-20 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200820_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='product',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='auctions.auctionslisting'),
            preserve_default=False,
        ),
    ]
