# Generated by Django 3.1 on 2020-08-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200820_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='product',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to='auctions.AuctionsListing'),
        ),
    ]
